# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  islab.re.kr:

services:

  centralbank.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=centralbank.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/artifacts/crypto-config/peerOrganizations/centralbank.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/artifacts/crypto-config/peerOrganizations/centralbank.islab.re.kr/peers/peer0.centralbank.islab.re.kr/msp:/etc/hypereledger/fabric/msp
      - ../build/artifacts/crypto-config/peerOrganizations/centralbank.islab.re.kr/peers/peer0.centralbank.islab.re.kr/tls:/etc/hypereledger/fabric/tls
    container_name: centralbank.islab.re.kr
    networks:
      - islab.re.kr

  commercialbank.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=commercialbank.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/artifacts/crypto-config/peerOrganizations/commercialbank.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/artifacts/crypto-config/peerOrganizations/commercialbank.islab.re.kr/peers/peer0.commercialbank.islab.re.kr/msp:/etc/hypereledger/fabric/msp
      - ../build/artifacts/crypto-config/peerOrganizations/commercialbank.islab.re.kr/peers/peer0.commercialbank.islab.re.kr/tls:/etc/hypereledger/fabric/tls
    container_name: commercialbank.islab.re.kr
    networks:
      - islab.re.kr

  consumer.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=consumer.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/artifacts/crypto-config/peerOrganizations/consumer.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/artifacts/crypto-config/peerOrganizations/consumer.islab.re.kr/peers/peer0.consumer.islab.re.kr/msp:/etc/hypereledger/fabric/msp
      - ../build/artifacts/crypto-config/peerOrganizations/consumer.islab.re.kr/peers/peer0.consumer.islab.re.kr/tls:/etc/hypereledger/fabric/tls
    container_name: consumer.islab.re.kr
    networks:
      - islab.re.kr

  orderer.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-orderer
      - FABRIC_CA_SERVER_CA_NAME=orderer.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "10054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/artifacts/crypto-config/ordererOrganizations/islab.re.kr:/etc/hyperledger/fabric-ca-orderer
    container_name: orderer.islab.re.kr
    networks:
      - islab.re.kr
